### ISSUE TITLE
Collision with a moving obstacle

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/social_force_window_planner#8]
Hello.
I am doing a simulation using sfwplanner. As I get closer to the pedestrian, the value of the social_work cost increases, but sometimes the cost value changes and sometimes it does not, even under the same conditions. When the value does not change, the value usually increases after the collision. This may be a problem with the specs of my PC, but is it a problem that can be solved by changing the parameters or the program?

**Comment by noeperez** [comment]
Hello, 
I am afraid you question is too vague. I need you to be more specific. 
If the cost is not changing, first, you must check if the pedestrian is being properly detected as a dynamic obstacle (pedestrian) or just as an obstacle. My guess is that the problem is in the perception side, and not here in the planner.

**Comment by hatta-yuuto** [comment]
Thank you.
