### ISSUE TITLE
How to display the candidates of best path

### ISSUE THREAD

**Issue by hatta-yuuto** [robotics-upo/social_force_window_planner#9]
Hello.
Thank you for everything.
I understand SFWPlanner generates multiple candidates for the orbit and selects the best orbit from them. Is it possible to display all the candidates on the screen?
I used rostopic echo to look at the /move_base/SFWPlannerROS/local_plan topic, but nothing was displayed. Also in rviz, when I tried to visualize /move_base/SFWPlannerROS/local_plan, nothing was displayed.
(On the other hand, I was able to confirm with rviz that /move_base/SFWPlannerROS/global_plan generates a route along the global path. ）

**Comment by noeperez** [comment]
Hello,

as you can see in [Line 47](https://github.com/robotics-upo/social_force_window_planner/blob/f735a960f715d8c5cfddc676df19ff0bafc53cba/src/sfw_planner_ros.cpp#L47) of sfw_planner_ros.cpp, a RViz MarkerArray called "trajectories" is published with the different trajectories evaluated for each time step.

**Comment by hatta-yuuto** [comment]
Thank you.
Have a happy new year.

**Comment by hatta-yuuto** [comment]
I'm sorry.
I just have one more question.
I have confirmed that the trajectories topic has been published, but I am getting the following error in rviz.

"points should not be empty for specified marker type. at least two points are required for a line_strip marker".

It may be a problem with my ros settings, but could you please check?

**Comment by noeperez** [comment]
Hello,

we are publishing a marker array, in which each marker is a line of points that represents the possible trajectory. Sometimes, some of these projected trajectories do not include at least the required two points to be visualized because the trajectory is too short (when robot velocity very low and projected velocities very low). That the error that you are watching. However, the rest of trajectories are visualized properly, so don't worry about that error.

**Comment by hatta-yuuto** [comment]
Thank you.
